config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'posts#index', as: 'home'

get 'about' => 'pages#about', as: 'about'

get '/logout' => 'users#logout', as: 'logout'
get '/login' => 'users#login', as: 'login'
get '/register' => 'users#register', as: 'register'
get '/sessions' => 'sessions#destroy', as: 'destroy'
get '/users/:id' => 'users#show', as: 'user'
post '/sessions' => 'sessions#create', as: 'sessions'
post '/create' => 'users#create'

get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
patch '/users/:id', to: 'users#update'
put '/users/:id', to: 'users#update'

resources :posts do
	resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5} 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

    helper_method :current_user,:logged_in?, :logged_in_user,:current_user, :is_admin?
    before_action :set_cache_buster

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def is_admin?
		if !current_user.nil? && !current_user.admin.nil?
			current_user.admin == true
		else
			current_user.nil?
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def logged_in_user
		unless logged_in?
			flash[:danger] = "Please log in."
			redirect_to sessions_path
		end
	end


	def current_user?(user)
		user == current_user
	end

	private
	def correct_user
      @user = User.find_by(id: session[:user_id])
      redirect_to(root_url)  unless current_user?(@user)
    end

    private
    def set_cache_buster
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	# http_basic_authenticate_with name: "admin", password: "qwert"

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@heading = 'About us'
		@text = 'Some text.'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "qwerty", 
	except: [:index, :show]

	def index
		@post = Post.all
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])

		@post.comments.destroy
		@post.destroy
		redirect_to posts_path
	end

	def create
		# render plain: params[:post].inspect
		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	private def post_params 
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  	end

	def create
		user = User.find_by(email:login_params[:email])
		if user && user.authenticate(login_params[:password])
			session[:user_id] = user.id
			session[:user_name] = user.email
			redirect_to home_path
		else
			flash[:login_errors] = ['Invalid credentionals']
			redirect_to login_path
		end

	end

	def destroy
		@current_user = nil
	    reset_session
	    redirect_to home_path
  	end
  	
	private
		def login_params
			params.require(:login).permit(:email, :password)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:new, :show, :edit]
    before_action :correct_user, only: [:new, :show, :edit]

    def index
      @users = User.all
    end

    def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to home_path
		else
			flash[:register_errors] = user.errors.full_messages
			redirect_to login_path
		end
	end

    def show
      @user = User.find_by(id: session[:user_id])
    end

    def edit
      	@user = User.find_by(id: session[:user_id])
    end

    def update
    	@user = User.find_by(id: session[:user_id])

		if(@user.update(edit_params))
			redirect_to @user
		else
			render 'edit'
		end
    end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin => false)
		end

		def edit_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :old_password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kravchuk Blog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-bold">Kravchuk Blog</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark"><%= link_to "Home", home_path %></span>
        <% if logged_in? && is_admin? %>
          <span class="p-2 text-dark"><%= link_to "Add Post", new_post_path %></span>
        <% end %>
        <span class="p-2 text-dark"><%= link_to "About us", about_path %></span>
         <% if logged_in? %>
           <span class="p-2 text-dark"><%= link_to current_user.name, user_path(current_user) %></span>
           <span class="p-2 text-dark"><%= link_to "Log out", destroy_path %></span>
         <% else %>
           <span class="p-2 text-dark"><%= link_to 'Sign In', login_path %></span>
         <% end %>
      </nav>
    </div>
  
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>

<p><%= @text %></p>

app/views/posts/edit.html.erb
<h2>Edit post</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Title<br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		State Text<br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h1>All posts</h1>
<% @post.each do |post| %>
<div class="alert alert-light">
	<h3><%= post.title %></h3>
	<p><%= post.body %></p>
	<%= link_to "More...", post_path(post), :class => 'btn btn-outline-primary' %>
</div>
<br>
<% end %>

app/views/posts/new.html.erb
<h2>Add new post</h2>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Title<br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		State Text<br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<% if logged_in? && is_admin? %>
	<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning' %>
	<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this post?"}, :class => 'btn btn-danger' %>
<% end %>
<hr>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
<div class="alert alert-light">
	<p><strong><%= comment.username %></strong>: <%= comment.body %></p>
</div>
<br>
<% end %>

<% if logged_in? %>
	<hr>
	<h2>Add comment</h2>
	<%= form_for([@post, @post.comments.build]) do |f| %>
		<p>
			User<br>
			<%= f.text_field(:username, {:class => 'form-control', :readonly => true, :value => current_user.name}) %>
		</p>
		<p>
			Comment text<br>
			<%= f.text_area(:body, {:class => 'form-control'}) %>
		</p>

		<p>
			<%= f.submit("Add comment", {:class => 'btn btn-warning'}) %>
		</p>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit profile</h2>
<%= form_for :user, url: user_path(@user), method: :patch do |f| %>
	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Username<br>
		<%= f.text_field(:name, {:class => 'form-control', :value => current_user.name}) %>
	</p>
	<p>
		Email<br>
		<%= f.text_area(:email, {:class => 'form-control', :value => current_user.email}) %>
	</p>
	<div class="form-group">
		<input type="password" name="user[password]" placeholder="new password" class="form-control mb-2">
		<input type="password" name="user[password_confirmation]" placeholder="new password confirmation" class="form-control">
	</div>

	<p>
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/users/login.html.erb
<!DOCTYPE html>

<html>
	<head>
		<title>Sign In</title>
	</head>	
	<body>
		<div class="wrapper fadeInDown">
  			<div id="formContent">
    		<!-- Tabs Titles -->
			<h1>Sign In</h1>

				<form action="/sessions" method="POST">
					<div class="form-group">
						<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
						<input type="email" name="login[email]" placeholder="email" class="form-control mb-2">
						<input type="password" name="login[password]" placeholder="password" class="form-control mb-2">
					</div>
					<input type="submit" name="submit" class="submit btn btn-outline-primary">
					<div class="container pl-0 ml-0">
						Don't have an account?<%= link_to "Sign Up", register_path, :class => 'link' %>
					</div>
				</form>

				<div class="errors">
					<% if flash[:login_errors]%>
					<% flash[:login_errors].each do |error| %>
						<p><%= error %></p>
						<% end %>
					<% end %>

				</div>
			</div>
		</div>
	</body>
</html>

app/views/users/register.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Sing Up</title>
</head>

<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <h1>Sign Up</h1>
            <form action="/create" method="POST">
                <div class="form-group">
                    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
                    <input type="name" name="user[name]" placeholder="name" class="form-control mb-2">
                    <input type="email" name="user[email]" placeholder="email" class="form-control mb-2">
                    <input type="password" name="user[password]" placeholder="password" class="form-control mb-2">
                    <input type="password" name="user[password_confirmation]" placeholder="password_confirmation" class="form-control">
                </div>
                <input type="submit" name="submit" class="submit btn btn-outline-primary">
                <div class="container pl-0 ml-0">
                    Already have an account?<%= link_to "Sign In", login_path, :class => 'link' %>
                </div>
            </form>
            <div class="errors">
                <% if flash[:register_errors] %>
                <% flash[:register_errors].each do |error| %>
                <p>
                    <%= error %>
                </p>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</body>

</html>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>
<h5><strong>email: </strong> <%= @user.email %></h5>
<hr>

<%= link_to "Edit Profile", edit_user_path, :class => 'btn btn-warning' %>